Add extra dynamic tags
Runnable/dogerode pull request #5
Opened 2016-09-26 22:01 UTC by podviaznikov

Pass extra tags that will be merged and reported with all tags to datadog.
Updated code to look more modern. Add standard.

2016-09-26 22:17 UTC, anandkumarpatel commented on index.js
>    'unpause',
can you add update?

2016-09-26 22:18 UTC, anandkumarpatel requested changes

2016-09-27 21:03 UTC, podviaznikov commented on index.js
>    'unpause',
done

2016-09-27 21:20 UTC, anandkumarpatel approved these changes

2016-09-27 21:20 UTC, merged